import { Link } from "wouter";
import { useState } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { SiteLayout } from "@/components/layout/site-layout";
import {
  Calendar,
  Clock,
  MapPin,
  Users,
  Building2,
  Rocket,
  Wallet,
  GraduationCap,
  Trophy,
  Lightbulb,
  TrendingUp,
  CheckCircle2,
  Handshake,
  Briefcase,
} from "lucide-react";

// Stats data matching the design
const stats = [
  { 
    label: "Companies Built", 
    value: "100+", 
    description: "Total number of legally incorporated startups built, funded, and launched through StartupUniv",
    highlighted: true
  },
  { 
    label: "Total Employees Created", 
    value: "2,500+", 
    description: "Total employment generated by companies built, funded, and launched through StartupUniv",
    highlighted: false
  },
  { 
    label: "Combined Annual Turnover", 
    value: "₹705 Cr+", 
    description: "Total annual revenue generated collectively by all active ventures built through StartupUniv",
    highlighted: false
  },
  { 
    label: "Total Valuation", 
    value: "₹2,860 Cr+", 
    description: "Aggregate valuation of all companies built, funded, and launched through StartupUniv",
    highlighted: false
  },
];

// Partner logos - matching the design
const partners = [
  { name: "T", logo: "/partners/t-logo.png", useText: true, textColor: "text-red-600", customLogo: true },
  { name: "NSDC", logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2XtUVJDx5XwJ4YodVWJU9qkSeNXAN96PbCg&s" },
  { name: "NAASCOM", logo: "https://d3r3sr3o54kk15.cloudfront.net/s3fs-public/styles/webp/public/media/media_kit/media_kit_2_7.jpg.webp?itok=9XtNFpgJ" },
  { name: "VTU", logo: "https://i0.wp.com/sjbit.edu.in/wp-content/uploads/2021/07/VTU-Logo-250x250-1.png?w=250&ssl=1" },
  { name: "AWS", logo: null, customLogo: true },
  { name: "ROOMANJAINX", logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEsJn8ActFqXe5E2aYpaSi0kTFGC-cOd3KNQ&s" },
  { name: "IBM", logo: null, customLogo: true },
];

// What Is StartupUniv cards
const whatIsCards = [
  {
    question: "Is It A Training Company?",
    answer: "No. Training Teaches About Entrepreneurship. We Put You Inside A Real Company From Day 1."
  },
  {
    question: "Is It An Incubator?",
    answer: "Not Exactly. Incubators Support Existing Startups. We Help You Become A Founder First."
  },
  {
    question: "Is It A University?",
    answer: "In Spirit, Not Structure. Universities Teach Theory. We Give You Real Execution."
  }
];

// Everything You Need cards
const buildStartupCards = [
  {
    title: "Legal & Financial Foundation",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
    items: [
      "Company incorporation",
      "Bank account setup",
      "Initial capital deployment",
      "Legal compliance support",
      "Accounting framework"
    ]
  },
  {
    title: "Team & Mentorship",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop",
    items: [
      "10-member dedicated team",
      "Business strategy mentor",
      "Technology execution mentor",
      "Operations & scaling mentor",
      "Weekly coaching sessions"
    ]
  },
  {
    title: "Market Access & Revenue",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600&fit=crop",
    items: [
      "100+ corporate partners (MAA)",
      "Government tender access",
      "Enterprise project pipeline",
      "Revenue generation support",
      "Contract execution guidance"
    ]
  }
];

// Benefits grid
const benefits = [
  {
    icon: Wallet,
    title: "₹10 Lakhs Seed Funding",
    description: "Seed capital per team to kickstart your venture with equity participation.",
    highlighted: true
  },
  {
    icon: Users,
    title: "Expert Mentorship",
    description: "Guidance from industry veterans, successful founders, and domain experts.",
    highlighted: false
  },
  {
    icon: Briefcase,
    title: "Stipend Support",
    description: "Monthly stipends for team members throughout the program.",
    highlighted: false
  },
  {
    icon: Handshake,
    title: "Corporate Connections",
    description: "Access to pilot projects and partnerships with leading corporates.",
    highlighted: false
  },
  {
    icon: GraduationCap,
    title: "Academic Credits",
    description: "Earn university recognized academic credits on program completion.",
    highlighted: false
  },
  {
    icon: Trophy,
    title: "Demo Day",
    description: "Pitch to investors, corporates, and industry leaders for funding and growth.",
    highlighted: false
  }
];

// MAA Program sections
const maaProgram = [
  {
    title: "Credibility by Association",
    description: "Link to empanelled companies with established credentials. Leverage their track record and eligibility for enterprise and government engagements.",
    color: "bg-[#F5D77E]"
  },
  {
    title: "Tender & Project Access",
    description: "Participate in large corporate and government tenders that would otherwise be inaccessible to early-stage startups. Supported execution on real projects.",
    color: "bg-[#C5CAE9]"
  },
  {
    title: "Early Revenue Enablement",
    description: "Secure execution opportunities and generate revenue while building product-market fit. Move beyond prototypes into sustainable operations.",
    color: "bg-[#F5B5B5]"
  }
];

// Promise sections
const promiseItems = [
  { condition: "Have an idea?", result: "We help you turn it into a real company" },
  { condition: "Don't have an idea?", result: "We help you discover and validate one" },
  { condition: "Worried about the risk?", result: "We absorb the early-stage risk" },
  { condition: "Want real experience?", result: "You work inside a real startup" },
  { condition: "Want equity?", result: "You earn it through execution" }
];

const buildRealStartup = [
  { condition: "The company is legally incorporated" },
  { condition: "Bank account opened in the company's name" },
  { condition: "₹10 lakh seed capital deposited" },
  { condition: "Equity allocated formally" },
  { condition: "Roles & responsibilities clearly defined" }
];

// Timeline
const timeline = [
  { days: "DAY 1-7", title: "ONBOARDING & INCORPORATION", description: "Company Legally Incorporated, Bank Account Opened, Team Formation Initiated. Initial Capital Deployed For Operations." },
  { days: "DAY 8-30", title: "TEAM BUILDING & PRODUCT SPRINT", description: "" },
  { days: "DAY 31-60", title: "MARKET VALIDATION & MAA MATCHING", description: "" },
  { days: "DAY 61-90", title: "FIRST CONTRACT EXECUTION", description: "" }
];

// Everything you need grid
const everythingGrid = [
  { week: "Week 1", title: "Real Company", subtitle: "Your startup is legally incorporated from day one this isn't a mock project or case study.", highlighted: true },
  { week: "Finance", title: "Real Bank Account & Capital", subtitle: "You operate with an actual business bank account and initial capital to manage expenses and growth.", highlighted: false },
  { week: "People", title: "Real Founders & Teams", subtitle: "Build alongside real co-founders and team members, just like an early-stage startup environment.", highlighted: false },
  { week: "Money", title: "Real Stipends", subtitle: "Get paid while building your startup no financial stress.", highlighted: false },
  { week: "Product", title: "Real Products", subtitle: "Create products meant for real users, real problems, and real market validation.", highlighted: false },
  { week: "Pressure", title: "Real Competition", subtitle: "Compete with startups through challenges and performance reviews.", highlighted: false },
  { week: "Funding", title: "Real Funding", subtitle: "Eligible startups can raise funding of up to ₹1 Crore based on traction and performance.", highlighted: false },
  { week: "Outcomes", title: "Real Careers & Startups", subtitle: "Graduate with real outcomes — a job, equity in a startup, or your own funded company.", highlighted: false }
];

// Problem domains
const problemDomains = [
  "Technology & Software",
  "Finance & Commerce",
  "Health & Life Sciences",
  "Education & Media",
  "Built Environment & Mobility",
  "Industry & Infrastructure",
  "Public & Enterprise",
  "Consumer & Lifestyle"
];

// Support benefits
const supportBenefits = [
  { title: "₹10L", description: "Each selected team receives dedicated seed capital to build, test, and launch their startup.", highlighted: false },
  { title: "Up to ₹1 Cr", description: "Additional funding for high-performing startups to grow and scale.", highlighted: false },
  { title: "Launch & Scale", description: "From launch to revenue, we support your go-to-market and sales journey.", highlighted: true },
  { title: "Workspace", description: "A fully equipped office environment with on-ground team support and shared operational resources.", highlighted: false }
];

// What You'll Achieve benefits
const achievementBenefits = [
  { 
    icon: Building2, 
    title: "Legally Incorporated Company", 
    description: "Not a prototype or simulation—a real business entity with all legal documentation and compliance.", 
    highlighted: true 
  },
  { 
    icon: Rocket, 
    title: "Functional Product/MVP", 
    description: "Working product built and tested with real users, ready for market deployment.", 
    highlighted: false 
  },
  { 
    icon: TrendingUp, 
    title: "Validated Business Model", 
    description: "Revenue model tested through MAA opportunities and real customer interactions.", 
    highlighted: false 
  },
  { 
    icon: CheckCircle2, 
    title: "Enterprise Access", 
    description: "Direct connections to 100+ corporate partners for tenders and project opportunities.", 
    highlighted: false 
  },
  { 
    icon: Handshake, 
    title: "Revenue-Generating Operations", 
    description: "Active contracts and revenue streams, moving beyond funding rounds.", 
    highlighted: false 
  },
  { 
    icon: Users, 
    title: "Experienced Team", 
    description: "Proven team of 10+ members with mentors across critical business functions.", 
    highlighted: false 
  }
];

// Safety net benefits
const safetyNetBenefits = [
  "Join other successful startups",
  "Transfer IP or talent", 
  "Real startup experience"
];

// Competition rewards
const competitionRewards = {
  directReward: "₹20L",
  directRewardDescription: "Direct Reward from StartupUniv",
  followOnFunding: "₹1Cr",
  followOnDescription: "Follow-on Funding (Equity / Debt)",
  additionalBenefits: [
    "Incubation Support",
    "GTM Strategy", 
    "Enterprise Access"
  ]
};

// AWS Logo SVG
const AWSLogo = () => (
  <svg width="80" height="50" viewBox="0 0 100 60" fill="none" xmlns="http://www.w3.org/2000/svg">
    <text x="50" y="25" fontFamily="Arial, Helvetica, sans-serif" fontSize="22" fontWeight="700" fill="#232F3E" textAnchor="middle">aws</text>
    <path d="M 20 40 Q 50 32 80 40" stroke="#FF9900" strokeWidth="4" fill="none" strokeLinecap="round" />
    <path d="M 76 37 L 80 40 L 76 43" stroke="#FF9900" strokeWidth="4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

// IBM Logo SVG
const IBMLogo = () => (
  <svg width="70" height="30" viewBox="0 0 100 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <text x="50" y="30" fontFamily="Arial Black, Arial, sans-serif" fontSize="32" fontWeight="900" fill="#1F70C1" textAnchor="middle" letterSpacing="2">IBM</text>
  </svg>
);

// T Logo (Red Hat style)
const TLogo = () => (
  <div className="w-12 h-16 flex items-center justify-center">
    <svg width="40" height="50" viewBox="0 0 40 50" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M20 5 C8 5 2 15 2 25 C2 40 15 45 20 48 C25 45 38 40 38 25 C38 15 32 5 20 5" fill="#CC0000" />
      <ellipse cx="20" cy="12" rx="12" ry="8" fill="#CC0000" />
    </svg>
  </div>
);

export default function HomePage() {
  const [imageErrors, setImageErrors] = useState<{[key: string]: boolean}>({});

  const handleImageError = (name: string) => {
    setImageErrors(prev => ({ ...prev, [name]: true }));
  };

  return (
    <SiteLayout>
      {/* Hero Section */}
      <section className="bg-[#FAF7F3] min-h-[90vh] flex items-center py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left Content */}
            <div className="space-y-6">
              <h1 className="text-fluid-hero font-serif font-normal text-gray-900">
                Welcome to<br />
                StartupUniv Where<br />
                Startups Begin
              </h1>
              
              <p className="text-gray-600 text-lg max-w-lg">
                StartupUniv is a bootcamp-style startup program that gives you mentors, teammates, funding, and hands-on support to turn ideas into real startups not just college projects.
              </p>

              <div className="flex flex-wrap gap-4">
                <Link href="/plans">
                  <Button className="bg-[#12333A] hover:bg-[#1B4752] text-white px-8 py-6 rounded-full text-lg font-medium">
                    Apply Now
                  </Button>
                </Link>
                <Link href="/program">
                  <Button variant="outline" className="border-2 border-[#12333A] text-[#12333A] hover:bg-[#12333A] hover:text-white px-8 py-6 rounded-full text-lg font-medium">
                    Explore Programs
                  </Button>
                </Link>
              </div>
            </div>

            {/* Right Content - Image with Quote */}
            <div className="relative">
              <div className="rounded-2xl overflow-hidden">
                <img 
                  src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&h=400&fit=crop"
                  alt="Team collaboration"
                  className="w-full h-auto object-cover"
                  fetchPriority="high"
                  loading="eager"
                  decoding="async"
                />
              </div>
              
              {/* Quote Card */}
              <div className="absolute bottom-0 right-0 left-0 md:left-auto md:right-0 md:bottom-0 md:w-3/4 bg-[#F5D77E] p-6 md:p-8 md:rounded-tl-2xl">
                <p className="text-xl md:text-2xl font-serif italic text-gray-900 mb-4">
                  "Students and professionals become job creators not job seekers"
                </p>
                <div className="flex items-center gap-4 text-sm text-gray-700">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    <span>4 Months</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    <span>Full time</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <MapPin className="w-4 h-4" />
                    <span>India</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-fluid-h2 font-serif font-normal text-gray-900 uppercase tracking-wide">
              WHERE IDEAS TURN INTO REAL STARTUPS
            </h2>
            <p className="text-xl md:text-2xl font-serif text-gray-900 uppercase tracking-wide mt-2">
              FROM CONCEPT TO CAPITAL
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <div 
                key={index} 
                className={`p-6 rounded-lg ${stat.highlighted ? 'bg-[#F5D77E]' : 'bg-white'} ${!stat.highlighted ? 'border border-gray-200' : ''}`}
              >
                <p className="text-sm font-medium text-gray-700 mb-2">{stat.label}</p>
                <p className="text-fluid-h1 font-bold text-gray-900 mb-3">{stat.value}</p>
                <p className="text-sm text-gray-600">{stat.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Partners Section */}
      <section className="bg-[#FAF7F3] py-16 md:py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-center text-gray-900 mb-12">
            Trusted by Industry Leaders
          </h2>
          
          <div className="flex flex-wrap justify-center items-center gap-8 md:gap-12 lg:gap-16">
            {partners.map((partner, index) => (
              <div key={index} className="flex flex-col items-center">
                {partner.customLogo && partner.name === "T" ? (
                  <TLogo />
                ) : partner.customLogo && partner.name === "AWS" ? (
                  <AWSLogo />
                ) : partner.customLogo && partner.name === "IBM" ? (
                  <IBMLogo />
                ) : partner.logo && !imageErrors[partner.name] ? (
                  <img 
                    src={partner.logo} 
                    alt={partner.name}
                    className="h-16 md:h-20 w-auto object-contain"
                    loading="eager"
                    decoding="async"
                    onError={() => handleImageError(partner.name)}
                  />
                ) : (
                  <div className="h-16 w-20 flex items-center justify-center bg-[#12333A] text-white font-bold rounded">
                    {partner.name.substring(0, 4)}
                  </div>
                )}
                <p className="text-xs text-gray-600 mt-2 uppercase tracking-wide">{partner.name}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What Is StartupUniv Section */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-2">
            What Is
          </h2>
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            StartupUniv ?
          </h2>

          <div className="border-t border-gray-300 mb-8"></div>

          <div className="grid md:grid-cols-3 gap-8 mb-12">
            {whatIsCards.map((card, index) => (
              <div key={index} className="border-t-2 border-gray-300 pt-6">
                <h3 className="text-xl font-serif font-medium text-gray-900 mb-4">{card.question}</h3>
                <p className="text-gray-600">{card.answer}</p>
              </div>
            ))}
          </div>

          {/* Image with overlay */}
          <div className="relative rounded-2xl overflow-hidden">
            <img 
              src="https://images.unsplash.com/photo-1464692805480-a69dfaafdb0d?w=1200&h=500&fit=crop"
              alt="Looking forward"
              className="w-full h-[400px] md:h-[500px] object-cover"
              loading="eager"
              decoding="async"
            />
            <div className="absolute bottom-0 left-0 bg-[#F5D77E] p-6 md:p-8 max-w-lg">
              <p className="text-lg md:text-xl font-serif text-gray-900">
                A Startup Sandbox where you explore entrepreneurship by building real companies with structured mentoring, team support, and managed early-stage risk.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Everything You Need to Build a Real Startup */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            Everything You Need to Build a Real Startup
          </h2>

          <div className="grid md:grid-cols-3 gap-6 mb-8">
            {buildStartupCards.map((card, index) => (
              <div key={index} className="relative rounded-2xl overflow-hidden group">
                <img 
                  src={card.image}
                  alt={card.title}
                  className="w-full h-[400px] object-cover"
                  loading="eager"
                  decoding="async"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent"></div>
                <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                  <h3 className="text-xl font-serif font-medium mb-2">{card.title}</h3>
                  <div className="border-t border-white/30 pt-4">
                    <ul className="space-y-2">
                      {card.items.map((item, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-sm">
                          <span className="text-white">•</span>
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="flex flex-wrap gap-4">
            <Link href="/plans">
              <Button className="bg-[#12333A] hover:bg-[#1B4752] text-white px-8 py-6 rounded-full text-lg font-medium">
                Apply Now
              </Button>
            </Link>
            <Link href="/program">
              <Button variant="outline" className="border-2 border-[#12333A] text-[#12333A] hover:bg-[#12333A] hover:text-white px-8 py-6 rounded-full text-lg font-medium">
                Explore Programs
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Everything You Need to Succeed */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            Everything You Need to Succeed
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
            {benefits.map((benefit, index) => (
              <Card key={index} className={`${benefit.highlighted ? 'bg-[#C5CAE9]' : 'bg-white'} border-0 shadow-none`}>
                <CardContent className="p-6">
                  <benefit.icon className="w-8 h-8 text-[#12333A] mb-4" />
                  <h3 className="text-lg font-serif font-medium text-[#12333A] mb-2">{benefit.title}</h3>
                  <p className="text-gray-600 text-sm">{benefit.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="flex flex-wrap gap-4">
            <Link href="/plans">
              <Button className="bg-[#12333A] hover:bg-[#1B4752] text-white px-8 py-6 rounded-full text-lg font-medium">
                Apply Now
              </Button>
            </Link>
            <Link href="/program">
              <Button variant="outline" className="border-2 border-[#12333A] text-[#12333A] hover:bg-[#12333A] hover:text-white px-8 py-6 rounded-full text-lg font-medium">
                Explore Programs
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* MAA Program Section */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h3 font-serif text-gray-900 mb-12">
            MAA Program: Market Access Built Into the Journey
          </h2>

          <div className="space-y-0">
            {maaProgram.map((item, index) => (
              <div key={index} className={`${item.color} p-8 md:p-12`}>
                <h3 className="text-fluid-h2 font-serif text-[#12333A] mb-4">{item.title}</h3>
                <p className="text-gray-700 max-w-3xl mb-6">{item.description}</p>
                <div className="flex flex-wrap gap-4">
                  <Link href="/plans">
                    <Button className="bg-[#12333A] hover:bg-[#1B4752] text-white px-6 py-3 rounded-full font-medium">
                      Apply Now
                    </Button>
                  </Link>
                  <Link href="/program">
                    <Button variant="outline" className="border-2 border-[#12333A] text-[#12333A] hover:bg-[#12333A] hover:text-white px-6 py-3 rounded-full font-medium">
                      Learn More
                    </Button>
                  </Link>
                </div>
              </div>
            ))}
          </div>

          {/* Decorative Pattern */}
          <div className="h-32 bg-gradient-to-r from-[#C5CAE9] via-[#F5D77E] to-[#F5B5B5] flex items-center justify-center overflow-hidden">
            <div className="flex gap-2">
              {[...Array(20)].map((_, i) => (
                <div key={i} className="w-12 h-12 rounded-full bg-white/20"></div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* The StartupUniv Promise */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            The StartupUniv Promise
          </h2>

          <div className="grid md:grid-cols-2 gap-8">
            {/* Left - No Matter Where You Start */}
            <div className="bg-[#F5D77E] rounded-2xl p-8">
              <Lightbulb className="w-10 h-10 text-[#12333A] mb-6" />
              <h3 className="text-xl font-serif font-medium text-[#12333A] mb-6">
                No Matter Where You Start, We Help You Build
              </h3>
              <div className="border-t border-[#12333A]/20 pt-6 space-y-4">
                {promiseItems.map((item, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-[#12333A] mt-0.5 flex-shrink-0" />
                    <p className="text-gray-800">
                      {item.condition} → {item.result}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Right - Build a Real Startup */}
            <div className="bg-white rounded-2xl p-8 border border-gray-200">
              <TrendingUp className="w-10 h-10 text-[#12333A] mb-6" />
              <h3 className="text-xl font-serif font-medium text-gray-900 mb-6">
                Build a Real Startup from Day One
              </h3>
              <div className="border-t border-gray-200 pt-6 space-y-4">
                {buildRealStartup.map((item, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-[#12333A] mt-0.5 flex-shrink-0" />
                    <p className="text-gray-700">{item.condition}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* From Idea to Revenue in 90 Days */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
                From Idea to Revenue in 90 Days
              </h2>

              <div className="space-y-8">
                {timeline.map((item, index) => (
                  <div key={index} className="border-b border-gray-300 pb-6">
                    <p className="text-sm font-medium text-gray-500 uppercase tracking-wide mb-2">{item.days}</p>
                    <h3 className="text-xl font-serif font-bold text-gray-900 uppercase tracking-wide">{item.title}</h3>
                    {item.description && (
                      <p className="text-gray-600 mt-2">{item.description}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-2xl overflow-hidden">
              <img 
                src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=700&fit=crop"
                alt="Working on laptop"
                className="w-full h-auto object-cover"
                loading="eager"
                decoding="async"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Everything you need to build a real startup - Grid */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            Everything you need to build a real startup
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {everythingGrid.map((item, index) => (
              <Card key={index} className={`${item.highlighted ? 'bg-[#F5D77E]' : 'bg-white'} border-0 shadow-none`}>
                <CardContent className="p-6">
                  <p className="text-sm font-medium text-gray-600 mb-1">{item.week}</p>
                  <div className="border-t border-gray-300 pt-4">
                    <p className="text-sm text-[#12333A] font-medium mb-1">{item.title}</p>
                    <p className="text-gray-700">{item.subtitle}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* We Work on Real Problems That Matter */}
      <section className="bg-[#FAF7F3] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h3 font-serif text-center text-gray-900 mb-8">
            We Work on Real Problems That Matter
          </h2>

          <div className="flex flex-wrap justify-center gap-3 mb-16">
            {problemDomains.map((domain, index) => (
              <span 
                key={index}
                className="px-4 py-2 bg-[#F5D77E] text-gray-900 rounded-md text-sm font-medium"
              >
                {domain}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Startup Support & Benefits */}
      <section className="bg-white py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            Startup Support & Benefits
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {supportBenefits.map((benefit, index) => (
              <Card key={index} className={`${benefit.highlighted ? 'bg-[#C5CAE9]' : 'bg-gray-50'} border-0 shadow-none`}>
                <CardContent className="p-6 text-center">
                  <Rocket className="w-12 h-12 text-[#12333A] mb-4 mx-auto" />
                  <h3 className="text-2xl font-serif font-bold text-gray-900 mb-3">{benefit.title}</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{benefit.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* What You'll Achieve */}
      <section className="bg-white py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-12">
            What You'll Achieve
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {achievementBenefits.map((achievement, index) => (
              <Card key={index} className={`${achievement.highlighted ? 'bg-[#F5D77E]' : 'bg-gray-50'} border-0 shadow-none h-full`}>
                <CardContent className="p-6">
                  <achievement.icon className="w-10 h-10 text-[#12333A] mb-4" />
                  <h3 className="text-xl font-serif font-semibold text-[#12333A] mb-3">{achievement.title}</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{achievement.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Build. Compete. Win Big. */}
      <section className="bg-white py-16 md:py-24">
        <div className="container mx-auto px-4">
          <h2 className="text-fluid-h2 font-serif text-gray-900 mb-4">
            Build. Compete. Win Big.
          </h2>
          
          <div className="bg-[#F3F4F6] rounded-2xl p-8 mb-8">
            <h3 className="text-2xl font-serif text-gray-900 mb-6">
              Winning Startup Receives
            </h3>
            
            <p className="text-gray-700 mb-8">
              Judged on product quality, execution, and team performance by industry experts
            </p>

            <div className="grid md:grid-cols-2 gap-6 mb-8">
              <Card className="bg-white border-0 shadow-lg">
                <CardContent className="p-6">
                  <h4 className="text-3xl font-serif font-bold text-gray-900 mb-2">{competitionRewards.directReward}</h4>
                  <p className="text-gray-700 text-sm">{competitionRewards.directRewardDescription}</p>
                </CardContent>
              </Card>
              
              <Card className="bg-white border-0 shadow-lg">
                <CardContent className="p-6">
                  <h4 className="text-3xl font-serif font-bold text-gray-900 mb-2">{competitionRewards.followOnFunding}</h4>
                  <p className="text-gray-700 text-sm">{competitionRewards.followOnDescription}</p>
                </CardContent>
              </Card>
            </div>

            <div className="flex flex-wrap gap-4 mb-8">
              {competitionRewards.additionalBenefits.map((benefit, index) => (
                <span 
                  key={index}
                  className="px-6 py-3 bg-[#C5CAE9] text-gray-900 rounded-full text-sm font-medium flex items-center gap-2"
                >
                  <span>{benefit}</span>
                  {benefit === "Incubation Support" && "🚀"}
                  {benefit === "GTM Strategy" && "📈"}
                  {benefit === "Enterprise Access" && "✅"}
                </span>
              ))}
            </div>
          </div>

          {/* Your Safety Net */}
          <div className="bg-[#12333A] rounded-2xl p-8 text-white">
            <div className="flex items-start gap-4 mb-6">
              <div className="w-12 h-12 bg-[#3B82F6] rounded-lg flex items-center justify-center">
                <CheckCircle2 className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-2xl font-serif font-semibold mb-2">
                  Your Safety Net
                </h3>
                <p className="text-gray-300">
                  Even if your startup doesn't win, you're never at a loss. Here's what you walk away with:
                </p>
              </div>
            </div>
            
            <div className="space-y-3">
              {safetyNetBenefits.map((benefit, index) => (
                <div key={index} className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-green-400 flex-shrink-0" />
                  <span className="text-white">{benefit}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Move from 8 million freshers ... */}
      <section className="bg-[#C5CAE9] py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="text-center">
            <h2 className="text-fluid-h3 font-serif text-[#12333A] leading-tight">
              Move from 8 million freshers to a small pool of experienced early-career professionals
            </h2>
          </div>
        </div>
      </section>

    </SiteLayout>
  );
}
